name: flutter_mvvm_counter
description: A simple Flutter app to demonstrate MVVM pattern

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.0 # 상태관리 라이브러리 사용

flutter:
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true 